# Generated by Django 4.1.3 on 2023-01-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giver",
            name="additional_information",
            field=models.CharField(default=123, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="giver",
            name="brief_introduction",
            field=models.CharField(default=123, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="giver",
            name="linkedin",
            field=models.URLField(default=123, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="giver",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
    ]
