# Generated by Django 4.1.3 on 2023-01-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_giver_additional_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giver",
            name="additional_information",
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="giver",
            name="linkedin",
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="feedback",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
