# Generated by Django 4.1.3 on 2023-01-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_giver_additional_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="feedback",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
