# Generated by Django 4.1.3 on 2023-01-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_meeting_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
