# Generated by Django 4.1.3 on 2023-01-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_meeting_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
