# Generated by Django 4.1.3 on 2023-01-11 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_user_firstname_user_lastname"),
    ]

    operations = [
        migrations.RemoveField(model_name="meeting", name="time",),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
