# Generated by Django 4.1.3 on 2023-01-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_remove_meeting_time_alter_meeting_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting", old_name="date", new_name="datetime",
        ),
    ]
