# Generated by Django 4.1.3 on 2023-01-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_rename_date_meeting_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="giver",
            name="timezone",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
