# Generated by Django 4.1.3 on 2023-03-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_giver_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="product_files/"),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
