# Generated by Django 4.1.3 on 2023-03-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="giver",
            name="stripe_access_token",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="giver",
            name="stripe_user_id",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
