# Generated by Django 5.0.1 on 2024-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_giver_stripe_access_token_giver_stripe_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='giver',
            name='minor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
