# Generated by Django 5.0.1 on 2024-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_major_alter_giver_minor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giver',
            name='minor',
        ),
        migrations.AddField(
            model_name='giver',
            name='grade_level',
            field=models.CharField(default='Freshman', max_length=100),
        ),
    ]
