# Generated by Django 5.0.1 on 2024-02-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_giver_minor_giver_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giver',
            name='grade_level',
            field=models.CharField(max_length=100),
        ),
    ]
