# Generated by Django 5.0.1 on 2024-02-11 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_giver_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='username',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='password',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.AddField(
            model_name='giver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiver',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giver',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giver',
            name='brief_introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='giver',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.RemoveField(
            model_name='giver',
            name='major',
        ),
        migrations.AlterField(
            model_name='giver',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='giver',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giver',
            name='major',
            field=models.ManyToManyField(related_name='givers', to='myapp.major'),
        ),
    ]
