# Generated by Django 5.0.1 on 2024-02-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_giver_email_remove_giver_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giver',
            name='timezone',
        ),
    ]
