# Generated by Django 5.0.1 on 2024-02-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_giver_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='calendly_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giver',
            name='calendly_webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
