# Generated by Django 5.0.1 on 2024-02-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_giver_calendly_link_giver_calendly_webhook_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giver',
            name='calendly_link',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='calendly_webhook_id',
        ),
    ]
