# Generated by Django 5.0.1 on 2024-02-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_giver_calendly_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
            ],
            options={
                'ordering': ['day', 'start_time', 'end_time'],
            },
        ),
        migrations.AddField(
            model_name='giver',
            name='availability',
            field=models.ManyToManyField(related_name='available_givers', to='myapp.availabletime'),
        ),
    ]
