# Generated by Django 5.0.1 on 2024-02-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_giver_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giver',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/user_profile.jpg', null=True, upload_to='images/'),
        ),
    ]
