# Generated by Django 5.0.1 on 2024-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_giver_availability_alter_giver_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='giver',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='givers', to='myapp.language'),
        ),
    ]
