# Generated by Django 5.0.1 on 2024-03-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_giver_grade_level_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giver',
            name='availability',
        ),
        migrations.AddField(
            model_name='availabletime',
            name='giver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='myapp.giver'),
        ),
    ]
