# Generated by Django 5.0.1 on 2024-03-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_availabletime_giver'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='availability',
            field=models.ManyToManyField(blank=True, null=True, related_name='available_givers', to='myapp.availabletime'),
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='myapp.giver'),
        ),
    ]
