# Generated by Django 5.0.1 on 2024-03-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_giver_availability_alter_availabletime_giver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='giver',
        ),
    ]
