# Generated by Django 5.0.1 on 2024-03-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_availabletime_giver'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='giver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='myapp.giver'),
            preserve_default=False,
        ),
    ]
