# Generated by Django 5.0.1 on 2024-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_rename_is_video_uploaded_meeting_is_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
