# Generated by Django 5.0.1 on 2024-03-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_meeting_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='giver_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='giver_meetings', to='myapp.giver'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='receiver_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiver_meetings', to='myapp.receiver'),
        ),
    ]
