# Generated by Django 5.0.1 on 2024-03-06 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='giver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='myapp.giver'),
        ),
    ]
