# Generated by Django 5.0.1 on 2024-03-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_receiver_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
