# Generated by Django 5.0.1 on 2024-03-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_giver_is_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='is_displaying',
            field=models.BooleanField(default=True),
        ),
    ]
