# Generated by Django 5.0.1 on 2024-03-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_giver_is_displaying'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='is_ongoing',
            new_name='is_failed',
        ),
    ]
