# Generated by Django 5.0.1 on 2024-03-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_remove_meeting_converted_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='timezone_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
