# Generated by Django 5.0.1 on 2024-03-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_meeting_timezone_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giver',
            old_name='stripe_access_token',
            new_name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='giver',
            name='stripe_user_id',
        ),
    ]
