# Generated by Django 5.0.1 on 2024-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_rename_stripe_access_token_giver_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='is_payout_setup',
            field=models.BooleanField(default=False),
        ),
    ]
