# Generated by Django 5.0.1 on 2024-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_meeting_is_failed_by_giver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='failed_reason_by_giver',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='failed_reason_by_receiver',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
