# Generated by Django 5.0.1 on 2024-03-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_meeting_failed_reason_by_giver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_link',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
