# Generated by Django 5.0.1 on 2024-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_meeting_zoom_link_meeting_zoom_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_start_url',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
