# Generated by Django 5.0.1 on 2024-03-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_meeting_zoom_start_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='giver',
            name='signature_data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
