# Generated by Django 5.0.1 on 2024-03-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_giver_signature_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='utc_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
